### ISSUE TITLE
subprocess.CalledProcessError:

### ISSUE THREAD

**Issue by ShaktiprasadM** [luglilab/Cytophenograph#16]
The code runs and shows markers included and excluded and then the error comes as :
"Traceback (most recent call last):
  File "/userdata/shakti/test2/../conda_envs/Cytophenograph/cytophenograph.v6.py", line 84, in <module>
    DictInfo["flowsom_adata"] = run.runflowsom()
  File "/userdata/shakti/conda_envs/Cytophenograph/PhenoFunctions_v6.py", line 845, in runflowsom
    subprocess.check_call(['Rscript', '--vanilla',
  File "/userdata/shakti/tools/mambaforge/envs/Cytophenograph6/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['Rscript', '--vanilla', '/userdata/shakti/conda_envs/Cytophenograph/flowsom.Rscript', '/userdata/shakti/test2/day17_output//tmp.csv', '/userdata/shakti/test2/day17_output/', '/userdata/shakti/test2/day17_output//FiguresFlowSOM/UMAP', '31']' returned non-zero exit status 1.

@@@Execution Error!"
![github_luglilab](https://github.com/luglilab/Cytophenograph/assets/119098992/de29c641-5057-4a02-ac90-8494802403d2)

**Comment by luglilab** [comment]
Hi,

could you update the conda environment with this yml file

[environment_Cytophenograph6.yml.zip](https://github.com/luglilab/Cytophenograph/files/15294442/environment_Cytophenograph6.yml.zip)

**Comment by ShaktiprasadM** [comment]
Thanks a lot. It was an error with the package FlowSOM, flowAI.  I
reinstalled them. Read your entire script and found the error is happening
at calling the Rscript part.
I had one more question. If I don't want to downsample, what should I do?

With Regards

Shaktiprasad Mishra

**Comment by luglilab** [comment]
Just run the analysis without setting the downsampling flag.
