### ISSUE TITLE
ValueError: unknown locale: UTF-8 [Mac OS]

### ISSUE THREAD

**Issue by luglilab** [luglilab/Cytophenograph#3]
During Installation: 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/simone/opt/anaconda3/envs/cytophenograph2/lib/python3.6/site-packages/anndata/__init__.py", line 7, in <module>
    from ._core.anndata import AnnData, ImplicitModificationWarning
  File "/Users/simone/opt/anaconda3/envs/cytophenograph2/lib/python3.6/site-packages/anndata/_core/anndata.py", line 18, in <module>
    from natsort import natsorted
  File "/Users/simone/opt/anaconda3/envs/cytophenograph2/lib/python3.6/site-packages/natsort/__init__.py", line 3, in <module>
    from natsort.natsort import (
  File "/Users/simone/opt/anaconda3/envs/cytophenograph2/lib/python3.6/site-packages/natsort/natsort.py", line 686, in <module>
    os_sort_key = os_sort_keygen()
  File "/Users/simone/opt/anaconda3/envs/cytophenograph2/lib/python3.6/site-packages/natsort/natsort.py", line 649, in os_sort_keygen
    return natsort_keygen(key=key, alg=ns.LOCALE | ns.PATH | ns.IGNORECASE)
  File "/Users/simone/opt/anaconda3/envs/cytophenograph2/lib/python3.6/site-packages/natsort/natsort.py", line 177, in natsort_keygen
    input_transform = utils.input_string_transform_factory(alg)
  File "/Users/simone/opt/anaconda3/envs/cytophenograph2/lib/python3.6/site-packages/natsort/utils.py", line 503, in input_string_transform_factory
    thou=re.escape(get_thousands_sep()), nodecimal=nodecimal
  File "/Users/simone/opt/anaconda3/envs/cytophenograph2/lib/python3.6/site-packages/natsort/compat/locale.py", line 73, in get_thousands_sep
    loc = ".".join(locale.getlocale())
  File "/Users/simone/opt/anaconda3/envs/cytophenograph2/lib/python3.6/locale.py", line 581, in getlocale
    return _parse_localename(localename)
  File "/Users/simone/opt/anaconda3/envs/cytophenograph2/lib/python3.6/locale.py", line 490, in _parse_localename
    raise ValueError('unknown locale: %s' % localename)
ValueError: unknown locale: UTF-8

**Comment by luglilab** [comment]
f you have faced the error on MacOS X, here's the quick fix - add these lines to your ~/.bash_profile:

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
